export const OPTION_PROPERTIES = [
  {
    option_property_id: 1,
    option_property_name: 'Red',
    option_property_additional_price: 0,
    option_property_base: true,
    option_id: 1,
  },
  {
    option_property_id: 2,
    option_property_name: 'Black',
    option_property_additional_price: 0,
    option_property_base: false,
    option_id: 1,
  },
  {
    option_property_id: 3,
    option_property_name: 'Blue',
    option_property_additional_price: 0,
    option_property_base: false,
    option_id: 1,
  },
  {
    option_property_id: 4,
    option_property_name: 'White',
    option_property_additional_price: 0,
    option_property_base: false,
    option_id: 1,
  },
  {
    option_property_id: 5,
    option_property_name: 'S',
    option_property_additional_price: 0,
    option_property_base: true,
    option_id: 2,
  },
  {
    option_property_id: 6,
    option_property_name: 'M',
    option_property_additional_price: 2000,
    option_property_base: false,
    option_id: 2,
  },
  {
    option_property_id: 7,
    option_property_name: 'L',
    option_property_additional_price: 5000,
    option_property_base: false,
    option_id: 2,
  },
  {
    option_property_id: 8,
    option_property_name: 'XL',
    option_property_additional_price: 7000,
    option_property_base: false,
    option_id: 2,
  },
];
