export const PRODUCTS_OPTIONS = [
  { product_id: 1, option_id: 1 },
  { product_id: 1, option_id: 2 },
  { product_id: 2, option_id: 1 },
  { product_id: 2, option_id: 2 },
  { product_id: 3, option_id: 1 },
  { product_id: 4, option_id: 1 },
  { product_id: 5, option_id: 1 },
  { product_id: 6, option_id: 1 },
  { product_id: 7, option_id: 1 },
  { product_id: 8, option_id: 1 },
  { product_id: 9, option_id: 1 },
  { product_id: 10, option_id: 1 },
  { product_id: 11, option_id: 1 },
  { product_id: 12, option_id: 1 },
  { product_id: 13, option_id: 1 },
  { product_id: 14, option_id: 1 },
  { product_id: 15, option_id: 1 },
  { product_id: 16, option_id: 1 },
];
