export const PRODUCTS = [
  {
    product_id: 1,
    product_name: 'Overweight Hoodie',
    product_price: 25000,
    small_category_id: 1,
  },
  {
    product_id: 2,
    product_name: 'Crop Hoodie',
    product_price: 20000,
    small_category_id: 1,
  },
  {
    product_id: 3,
    product_name: 'Crop T-shirt',
    product_price: 12000,
    small_category_id: 2,
  },
  {
    product_id: 4,
    product_name: 'Character T-shirt',
    product_price: 13000,
    small_category_id: 2,
  },
  {
    product_id: 5,
    product_name: 'Half Pants',
    product_price: 17000,
    small_category_id: 3,
  },
  {
    product_id: 6,
    product_name: 'Wide-fit Pants',
    product_price: 18000,
    small_category_id: 3,
  },
  {
    product_id: 7,
    product_name: 'Cross Bag',
    product_price: 30000,
    small_category_id: 5,
  },
  {
    product_id: 8,
    product_name: 'Tote Bag',
    product_price: 32000,
    small_category_id: 5,
  },
  {
    product_id: 9,
    product_name: 'Eco Bag',
    product_price: 15000,
    small_category_id: 5,
  },
  {
    product_id: 10,
    product_name: 'Necklace',
    product_price: 18500,
    small_category_id: 7,
  },
  {
    product_id: 11,
    product_name: 'Steel Ring',
    product_price: 16000,
    small_category_id: 7,
  },
  {
    product_id: 12,
    product_name: 'Square Tin Case',
    product_price: 10000,
    small_category_id: 8,
  },
  {
    product_id: 13,
    product_name: 'Circle Tin Case',
    product_price: 11000,
    small_category_id: 8,
  },
  {
    product_id: 14,
    product_name: 'Long Mouse Pad',
    product_price: 16000,
    small_category_id: 9,
  },
  {
    product_id: 15,
    product_name: 'Short Mouse Pad',
    product_price: 14000,
    small_category_id: 9,
  },
  {
    product_id: 16,
    product_name: 'Clip Pen',
    product_price: 8000,
    small_category_id: 10,
  },
];
